name: Terraform CI/CD Destroy on AWS

on:
  workflow_dispatch:

env:
  TF_WORKING_DIR: ./terraform
  AWS_REGION: us-east-1

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform Init with Backend Config
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false \
            -backend-config="bucket=terraform-state-dan-vuln" \
            -backend-config="dynamodb_table=terraform-lock-dan-vuln" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve
