name: Terraform CI/CD on AWS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TF_WORKING_DIR: ./terraform
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: Terraform Plan & Apply with Import
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform Init with Backend Config
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false \
            -backend-config="bucket=terraform-state-dan-vuln" \
            -backend-config="dynamodb_table=terraform-lock-dan-vuln" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Import existing resources (if not already imported)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          # Check if insecure_role is already imported
          if ! terraform state list | grep -q '^aws_iam_role.insecure_role$'; then
            terraform import aws_iam_role.insecure_role insecure-role
          else
            echo "aws_iam_role.insecure_role already imported"
          fi

          if ! terraform state list | grep -q '^aws_iam_role_policy_attachment.insecure_role_attach$'; then
            terraform import aws_iam_role_policy_attachment.insecure_role_attach insecure-role/arn:aws:iam::533267171879:policy/insecure-policy
          else
            echo "aws_iam_role_policy_attachment.insecure_role_attach already imported"
          fi

          if ! terraform state list | grep -q '^aws_iam_instance_profile.insecure_instance_profile$'; then
            terraform import aws_iam_instance_profile.insecure_instance_profile insecure-instance-profile
          else
            echo "aws_iam_instance_profile.insecure_instance_profile already imported"
          fi

          if ! terraform state list | grep -q '^aws_vpc.insecure_vpc$'; then
            terraform import aws_vpc.insecure_vpc vpc-060788fed16db44f3
          else
            echo "aws_vpc.insecure_vpc already imported"
          fi

          if ! terraform state list | grep -q '^aws_internet_gateway.igw$'; then
            terraform import aws_internet_gateway.igw igw-026f3463bfc405867
          else
            echo "aws_internet_gateway.igw already imported"
          fi

          if ! terraform state list | grep -q '^aws_subnet.public_a$'; then
            terraform import aws_subnet.public_a subnet-0cf91d99424e8500d
          else
            echo "aws_subnet.public_a already imported"
          fi

          if ! terraform state list | grep -q '^aws_subnet.public_b$'; then
            terraform import aws_subnet.public_b subnet-0f2ceffe005c087f5
          else
            echo "aws_subnet.public_b already imported"
          fi

          if ! terraform state list | grep -q '^aws_security_group.insecure_sg$'; then
            terraform import aws_security_group.insecure_sg sg-xxxxxxxxxxxxxxxxx
          else
            echo "aws_security_group.insecure_sg already imported"
          fi

          if ! terraform state list | grep -q '^aws_security_group.open_sg$'; then
            terraform import aws_security_group.open_sg sg-0eace4e9d4f574026
          else
            echo "aws_security_group.open_sg already imported"
          fi

          if ! terraform state list | grep -q '^aws_route_table.public_rt$'; then
            terraform import aws_route_table.public_rt rtb-09a2db16e587c5094
          else
            echo "aws_route_table.public_rt already imported"
          fi

          if ! terraform state list | grep -q '^aws_route_table_association.public_a_assoc$'; then
            terraform import aws_route_table_association.public_a_assoc rtbassoc-0d62c83a2bf129f28
          else
            echo "aws_route_table_association.public_a_assoc already imported"
          fi

          if ! terraform state list | grep -q '^aws_route_table_association.public_b_assoc$'; then
            terraform import aws_route_table_association.public_b_assoc rtbassoc-0acc965da1dd54f7b
          else
            echo "aws_route_table_association.public_b_assoc already imported"
          fi

          if ! terraform state list | grep -q '^aws_network_acl.open_acl$'; then
            terraform import aws_network_acl.open_acl acl-0bb20cea9e345760f
          else
            echo "aws_network_acl.open_acl already imported"
          fi

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=tfplan

      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}/tfplan

      - name: Show Plan Summary
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform show -no-color tfplan

  apply:
    name: Terraform Apply
    needs: terraform
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Init with Backend Config
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false \
            -backend-config="bucket=terraform-state-dan-vuln" \
            -backend-config="dynamodb_table=terraform-lock-dan-vuln" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
